@UTF8
-PRESP		"*-PRESP"
r-in		"in"
r-on		"on"
-PL		"*-PL"
&PAST		"*&PAST"
|*,~|poss	"~poss|*"
|cop -|*,~|cop	"cop|*"
|det:art	"det:art"
-PAST		"*-PAST"
-3S		"*-3S"
&3S		"*&3S"
|aux -|*,~|aux	"aux|*"
|*,~|cop	"~cop|*"
|*,~|aux	"~aux|*"
